### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by bartavelle** [agrafix/elm-bridge#1]
Here are a few bugs I uncovered:

 * [This](https://github.com/agrafix/elm-bridge/blob/2b91400c2fc53f304e10c39ca10a94de499cd5fd/src/Elm/Json.hs#L86) should be `\\v` instead of `\v`
 * On the same line, this isn't properly parsed by my elm compiler in many cases. It needs proper indentation.
 * There are several cases where matching closing parens are omited, and even the tests don't parse.

I am currently working on this module, with an eye on parameterizing it with the `Options` type from `aeson`, so that my instances will be compatible even in the presence of strange customization. I added quite a bit of code (support for alternative sum encoding schemes, sum types with records, map-like structures). It is pretty much out of the scope of your project because of the dependency on `aeson`, but let me know if you would be interested in merging some of it.

**Comment by agrafix** [comment]
I think that's a great idea, and the dependency on `aeson` should not be a problem as it is the defacto standard json library for haskell. Looking forward to your pull request! Did you add unit tests? I think that would be very important to catch the bugs you mentioned above...

**Comment by bartavelle** [comment]
I did add a pair of unit test and did fix those with the missing parens.

However this is currently quite a mess, I will send you the PR as soon as the code is more stable on my side. The PR will be quite large too ...

**Comment by agrafix** [comment]
:+1:
