### ISSUE TITLE
Update for Elm version 0.17

### ISSUE THREAD

**Issue by Kyarigwo** [agrafix/elm-bridge#13]
I have updated my pull request for updating to Elm version 0.17.  The changes that I have made are:

Add a new module, Elm.Versions exporting a type 
data ElmVersion
  = Elm0p16
  | Elm0p17

Modify Elm.Module, adding a function 
MakeElmModuleWithVersion which takes an ElmVersion as it's first parameter, hence switching on version, and modified the existing makeElmModule to be makeElmModuleWithVersion Elm0p16, so that existing code should run without any changes.

Finally, I have added two tests to ModuleSpec, one to test makeElmModuleWithVersion for Elm0p16 and one for Elm0p17.

Please suggest any changes.

**Comment by agrafix** [comment]
Merged in #12
