### ISSUE TITLE
Incompatible with latest Json.Decode on Elm 0.18.0?

### ISSUE THREAD

**Issue by ahri** [agrafix/elm-bridge#17]
The line `import Json.Decode exposing ((:=))` in the output generated by elm-bridge results in:

    Module `Json.Decode` does not expose `:=`

on Elm 0.18.0. I'm not sure if I messed something up!

**Comment by bartavelle** [comment]
Oh yeah, that is a bug! It should be `Json.Helpers`.

**Comment by bartavelle** [comment]
Do you get valid code with the last commit?

**Comment by bartavelle** [comment]
[of course I broke the build, it should be fine now]

**Comment by fendor** [comment]
It is still not fixed *push*

**Comment by bartavelle** [comment]
I do not have maintainer access on hackage, so that would mean @agrafix !

**Comment by agrafix** [comment]
@bartavelle I've now added you as maintainer, feel free to cut the release, I'm pretty busy until the weekend.

**Comment by bartavelle** [comment]
Pushed 0.4.1.
