### ISSUE TITLE
Converting sum types

### ISSUE THREAD

**Issue by MartinPotier** [agrafix/elm-bridge#21]
Hi,

I'm trying to convert my Haskell `Either a b` to an Elm `Either a b` but the encoder and decoder for this are… weird. It creates jsonDecEither and jsonEncEither decoders that need 2 arguments! I'd expect a set of encoder/decoder per constructor. Are sum types supported?

Nice job by the way, for all the rest it's been working like a charm!

**Comment by MartinPotier** [comment]
Still, the implementation of `jsonDecEither`/`jsonEncEither` is on me, right?

**Comment by bartavelle** [comment]
But it really depends on how you encoded your sum type! What is its shape, in json, for both the left and right cases? Also, would it be generic (can you encode `Either String String`) ?

**Comment by MartinPotier** [comment]
Hmm, you are right, I should look into the encoding of the sum type. It was automatically derived using generics.

**Comment by MartinPotier** [comment]
Closing this for now, as it *may* not be a problem of elm-bridge.

**Comment by bartavelle** [comment]
Just a note : you will usually need a tag of some sort for your encoding to be generic. For example, this could be an encoding for `Either String String`:

    {"left":"bar"}
    {"right":"foo"}
