### ISSUE TITLE
Support For Haskell Type Alias

### ISSUE THREAD

**Issue by theNerd247** [agrafix/elm-bridge#25]
```
type A = String 
data Foo = Foo 
  { a :: A
  }
```
produces
```
type alias Foo = 
  { a :: A
  }
```
Which gives the error that the type `A` isn't defined. Is there support for recursively deriving types?

**Comment by bartavelle** [comment]
There is support for newtypes, but not for type aliases. I rarely use them, so I could get away with just declaring the type alias on the Elm side every time ...

**Comment by bartavelle** [comment]
(Given the way it works right now, "fixing" it would require deriving an elm definition for the type alias too.)

**Comment by theNerd247** [comment]
Ok. I tried to use TypeSynonym instances as shortcut. Thanks for the try however it looks like the [elm-export][https://github.com/krisajenkins/elm-export] package has what I need. I can keep this open however for future users.

**Comment by bartavelle** [comment]
Not sure what my brain is made of some days. My last commit (from January the 11th) added support for newtypes, exactly what you needed :/ It is not on hackage yet though. Let me know if you still would like to use elm-bridge and I will produce a release.

**Comment by bartavelle** [comment]
I am working of having a more robust newtype support.
