### ISSUE TITLE
Preparing the elm-package

### ISSUE THREAD

**Issue by bartavelle** [agrafix/elm-bridge#3]
I published a formatted version of the elm package for testing, but I do not know why my code samples are truncated :(

I will keep on testing with a pair of real life projects until all of this is stable enough.

**Comment by agrafix** [comment]
What exactly do you mean by truncated? Can you show an example?

**Comment by bartavelle** [comment]
In http://package.elm-lang.org/packages/bartavelle/json-helpers/1.0.0/Json-Helpers, look at the beginning of the chapter "Encoding schemes". The sum type has 3 members in the source code ...

**Comment by bartavelle** [comment]
I mean 3 constructors.

**Comment by agrafix** [comment]
Looks like a bug in elms documentation generator... :-/

**Comment by bartavelle** [comment]
I have pushed a usable version of the elm package. I also have just pushed some changes in the elm-bridge package. I believe it is now releasable on hackage!

There are still pain points (for example I don't like how I created an `ElmOptions` type to account for newtype declarations, it probably should be decided during the json generation!).

What do you think ?

**Comment by agrafix** [comment]
A very important change would be to document somewhere which elm library in which version is needed to be compatible. Could you also update the example? Apart from that I think we can cut another release. Please add your self as author the license and cabal file :-)

**Comment by bartavelle** [comment]
Done!

**Comment by bartavelle** [comment]
If it's ok with you I'll add it to stackage as soon as the release is made.

**Comment by bartavelle** [comment]
Or perhaps I will not as the aeson bug isn't fixed yet :(

**Comment by agrafix** [comment]
Is our needed `aeson` version to high?

**Comment by bartavelle** [comment]
The currently required version is 0.9.*, but nightly now uses 0.10.*. I am waiting for the new release because it contains a blocking bug ...

**Comment by agrafix** [comment]
Could you reference the aeson issue here?

**Comment by bartavelle** [comment]
https://github.com/bos/aeson/issues/293

**Comment by bartavelle** [comment]
I suppose the stack issue itself is : https://github.com/bos/aeson/issues/328

**Comment by agrafix** [comment]
I'll still release this to hackage and then we can make a minor release as soon as the stack issue is resolved.

**Comment by bartavelle** [comment]
Sounds good to me!

**Comment by bartavelle** [comment]
It will probably not be a minor release though, as the `Options` field has changed in 0.10.*!

A solution to this would be to alter the code right now, drop the `ElmOptions` type, and find a nice API to decide when to newtype stuff.

**Comment by agrafix** [comment]
Sadly I'm currently not using this library anymore (We switched to https://github.com/typed-wire/typed-wire ), so it's up to you what will suit you best for your usecase. It would be cool if you could provide release notes for this release? :-)

**Comment by bartavelle** [comment]
Let's wait on it a bit, I will do the refactoring in a few days and figure out a solution. I didn't realize this `typed-wire` project existed!

What did you have in mind for the release notes ? A changelog-like new file in the repo ?

**Comment by agrafix** [comment]
Yes, a changelog file would be great, just something so I can write up notes like this: https://github.com/agrafix/Spock/releases

**Comment by bartavelle** [comment]
I just pushed a very succint changelog. Is that what you had in mind? The way newtypes are handled is now independant of instance generation, so `aeson` `Option` type is all that is needed. This means it will be possible to upgrade to later versions with a minor version bump.

**Comment by agrafix** [comment]
Cool thank's! So we are ready for release? :-)

**Comment by bartavelle** [comment]
I sure am!

**Comment by agrafix** [comment]
Release is up on hackage :-)

**Comment by bartavelle** [comment]
great!
