### ISSUE TITLE
ETypeDef instances for base types

### ISSUE THREAD

**Issue by tmbull** [agrafix/elm-bridge#31]
Hi, I am looking at porting `servant-elm` to `elm-bridge` or creating a similar library that works with `elm-bridge`. The reason being is that I really like that `elm-bridge` generates types that are "aeson compatible" , and that `elm-bridge` is more flexible in types that it supports (ie. sum types). 

However, one current stumbling block is that a servant JSON API can be created that returns any type with a FromJSON instance. Since `aeson` has built-in instances for most base types ([a], Either, Maybe, etc.) and a lot of common types (like Text), there's a lot of types that will work out of the box in servant responses that don't have ETypeDef instances. 

Do you think it makes sense to include default instances for types that already have analogs in Elm? Or do you think there is a better approach to solving this problem? Thanks.

**Comment by bartavelle** [comment]
That is a good question that I cannot really answer easily. For things like `[a]`, it just requires using the `list` combinator. However, for `Either` and `Maybe`, one solution could be to add them to the `json-helper` library, that is supposed to work with `elm-bridge`. Is that acceptable?

**Comment by tmbull** [comment]
I agree that it makes sense to add Elm helpers to the `json-helper` library where necessary. However, my use case is a little different than what is currently supported by `elm-bridge`... 

To give a little background, in case you are not familiar with servant, the `servant-foreign` package provides helpers for generating clients to servant APIs. You first have to implement the `HasForeignType` class (here)[https://hackage.haskell.org/package/servant-foreign-0.11.1/docs/Servant-Foreign.html#t:HasForeignType], which tells servant how to convert the types in your API (whether they be response bodies, request bodies, query params, path params, etc.) to your "foreign" language. In my case, I have defined an instance as follows: 

```
instance (IsElmDefinition a) => HasForeignType LangElm ETypeDef a where
  typeFor _ _ _ =
    compileElmDef (Proxy :: Proxy a)

```

This works fine for any response or request body that is of a type that I generate using `elm-bridge`. However, This doesn't work for example, a response body of type `[Foo]`. Maybe this could be solved by creating an instance of `IsElmDefinition` like:

```
instance (IsElmDefinition a) => [a] where
  compileElmDef = ...
```

The same thing could be done for Maybe, and other types that exist in both Haskell and Elm. There are a few other requirements unique to my use case, but I would like to know if this makes sense first. I understand that what I am asking for is beyond the original scope of `elm-bridge`.

**Comment by bartavelle** [comment]
This makes sense. It would require adding the same instances that are in aeson then. I will look into it.

**Comment by tmbull** [comment]
Thanks! If you have any questions or need any help, let me know.

**Comment by bartavelle** [comment]
I do not think I fully grasp what is required. `IsElmDefinition` will generate a type definition, and code for a serializer/deserializer. But they should not be generated for the cases you mentioned. Don't you need the `jsonSerForType` function to be exported too?

**Comment by tmbull** [comment]
I understand why you say that the type definition (and serializer/deserializer) should not be generated for the base types I mentioned.

I was looking into some more examples of code generators that use `servant-foreign` today, and I think I have an idea that might not require any additional code in `elm-bridge`, though I do think it will require `jsonSerForType` to be exported. Let me experiment a little more, and I'll update the issue with my findings.
