### ISSUE TITLE
Support aeson 0.11

### ISSUE THREAD

**Issue by agrafix** [agrafix/elm-bridge#4]
See https://github.com/fpco/stackage/issues/1211

@bartavelle , would you like to give this a shot?

**Comment by bartavelle** [comment]
I'll make it compile but I won't be able to try the end-to-end tests for the next 10 days.

**Comment by bartavelle** [comment]
The compilation issue should be fixed with the latest patch. There probably will be a bug if someone tries to play with the new `unwrapUnaryRecords` option. I will fix the code when I'll have access to my main computer.
