### ISSUE TITLE
Lambda paramaters fail Elm 0.19 shadowing rules

### ISSUE THREAD

**Issue by SebastianKG** [agrafix/elm-bridge#43]
`elm-bridge` generates
```
jsonEncUserInput : UserInput -> Value
jsonEncUserInput  val =
    let keyval v = case v of
                    Disconnected  -> ("Disconnected", encodeValue (Json.Encode.list identity []))
                    KeyDown v1 -> ("KeyDown", encodeValue (jsonEncKey v1))
                    KeyUp v1 -> ("KeyUp", encodeValue (jsonEncKey v1))
                    MoveFromTo v1 v2 -> ("MoveFromTo", encodeValue (Json.Encode.list identity [(\(v1,v2) -> Json.Encode.list identity [(Json.Encode.int) v1,(Json.Encode.int) v2]) v1, (\(v1,v2) -> Json.Encode.list identity [(Json.Encode.int) v1,(Json.Encode.int) v2]) v2]))
                    MoveNSizedPieceTo v1 v2 -> ("MoveNSizedPieceTo", encodeValue (Json.Encode.list identity [Json.Encode.int v1, (\(v1,v2) -> Json.Encode.list identity [(Json.Encode.int) v1,(Json.Encode.int) v2]) v2]))
    in encodeSumObjectWithSingleField keyval val
```
for Haskell types like
```
data UserInput
  = Disconnected
  | KeyDown Key
  | KeyUp Key
  | MoveFromTo (Int, Int)
               (Int, Int)
  | MoveNSizedPieceTo Int
                      (Int, Int)
```
which causes Elm 0.19 compiler errors such as
```
-- SHADOWING ------------- ./Communication/WebSocket/Compiled/ClientToServer.elm

These variables cannot have the same name:

55|                     MoveFromTo v1 v2 -> ("MoveFromTo", encodeValue (Json.Encode.list identity [(\(v1,v2) -> Json.Encode.list identity [(Json.Encode.int) v1,(Json.Encode.int) v2]) v1, (\(v1,v2) -> Json.Encode.list identity [(Json.Encode.int) v1,(Json.Encode.int) v2]) v2]))
                                   ^^                         ^^
Think of a more helpful name for one of them and you should be all set!

Note: Linters advise against shadowing, so Elm makes “best practices” the
default. Read <https://elm-lang.org/0.19.0/shadowing> for more details on this
choice.
```
Since at least one issue has been closed in the past for 0.19 support (https://github.com/agrafix/elm-bridge/issues/37), I had assumed the library was ready for Elm 0.19 -- I am not sure what your expectation of 0.19 compatibility actually is.

**Comment by bartavelle** [comment]
Oh, is variable name shadowing forbidden now? The library is currently more or less unmaintained, because I did not move to 0.19. This looks like it could be fixed though.

**Comment by bartavelle** [comment]
I just pushed something, does that help?

**Comment by ekalosak** [comment]
Is there any running effort to get this revved up for Elm-0.19? @bartavelle

**Comment by bartavelle** [comment]
Not really right now, at least not from me. I am not using Elm anymore, so that makes it hard for my to find the motivation to do this over something else in my free time ...

**Comment by ekalosak** [comment]
That's fair, thanks for taking the time to respond.
I'm using elm-bridge successfully with Elm 0.19, believe it or not... I'm guessing there are some more bespoke features I'll run into incompatibility issues with sooner or later. Are there any glaring ones that come to mind?

**Comment by bartavelle** [comment]
Hum not really, I would try to fix them if it is not too much work!

**Comment by schoettl** [comment]
Oh @bartavelle! Looks like you fixed the nested tuple shadowing issue in May 2022. Thank you! I just tried to reproduce this bug in current master and could not because it's already fixed. :D

Can we publish this as a new version to hackage? I just stumbled on this problem and was close to manually patching the generated encoders...

**Comment by bartavelle** [comment]
uploaded 0.8.1 ! Sorry for the huge delay :'(
