### ISSUE TITLE
Don't use "reserved" names in generated Elm code

### ISSUE THREAD

**Issue by agrafix** [agrafix/elm-bridge#8]
What should we do when elm-bridge generates an Elm type or record label that is reserved (like `type`  or `Int`)

**Comment by bartavelle** [comment]
There currently is that: src/Elm/Utils.hs

**Comment by agrafix** [comment]
Ah, great! What about constructors/types like Int? We can apply transformations to the Haskell constructor, so if we have "FooInt" in Haskell, we might get just "Int" in Elm.

**Comment by bartavelle** [comment]
I added some knobs in the `Elm.Module` module, which defaults to this https://github.com/agrafix/elm-bridge/blob/33f23bb3fc5883b5630ae3ad9238b039b3844490/src/Elm/Module.hs#L89-L110.
